### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by kameronton** [SEM1INFOENS/multiplanner#4] opened 2018-10-11 19:43 UTC
The interface should feature notifications reminding users of nearing events. Reminders should be configurable: enabled/disable, delay.

**Comment by Z-ephyr** [comment] 2018-12-14 21:17
Maybe we could use https://github.com/django-notifications/django-notifications

**Comment by Z-ephyr** [comment] 2018-12-31 19:17
https://github.com/pinax/pinax-notifications could be good as well

**Comment by Z-ephyr** [comment] 2018-12-31 20:40
It seems to me that pinax might be better

**Comment by Z-ephyr** [comment] 2019-01-01 16:12
@MaloPerez So I installed successfully pinax-notification, but for the moment I don't manage to create a notification.
My last commit was a test for creating one that did not do anything (it was supposed to send a stupid notification like "XXX wants to be your friend" with XXX your user name).

Unfortunately, I did not manage to find any kind of tutorial and their readme does not give much information.
This person seems to have it working https://stackoverflow.com/questions/4505941/sending-notifications-to-your-friends-in-pinax-django
If we don't manage to make it work, we could start looking for projects using pinax-notifications and look at their source code

This is a more concise version of the readme focusing on making it work https://github.com/synasius/pinax-notifications/blob/master/docs/usage.md

**Comment by Z-ephyr** [comment] 2019-01-01 16:13
https://templates.pinaxproject.com/notifications/settings/ This is nice, it would be great to use it :)

**Comment by Z-ephyr** [comment] 2019-01-04 09:37
I don't know what this is worth, but from what they say `pinax-notifications` does not seem to be what we were looking for :( https://www.it.iitb.ac.in/frg/wiki/images/9/9f/Project02_Presentation_02_2018_05_25.pdf

And though `django-notifications` is now compatible with Python 3.6 and Django 2.0, their github repository does not state if it is compatible with Django 2.1 (that we are using)

I am therefore giving up `pinax-notifications` and trying to set up `django-notify-x` (https://github.com/v1k45/django-notify-x), which contrary to the two aforementioned apps, have a documentation... So I am starting a new branch called `notifications-notify` (I keep the old branch just in case)

**Comment by MaloPerez** [comment] 2019-01-04 10:20
Do you want me to do anything is particular ?

**Comment by Z-ephyr** [comment] 2019-01-04 22:30
Well if you have time to work on it, it would be nice ! My first commit was about installing and setting up (part getting started of the doc), now it would be great to make it work and sending a first notification (even nonsensical) would be great. I'll try to keep working on it tomorrow, but help is welcome :)
Link to the doc : https://django-notify-x.readthedocs.io/en/latest/index.html

**Comment by Z-ephyr** [comment] 2019-01-05 12:03
I have the same problem :( I don't manage to display a notification

**Comment by Z-ephyr** [comment] 2019-01-05 12:31
Checking http://localhost:8000/admin/notify/notification/ I see that the notification is created, but is simply not displayed :(

**Comment by Z-ephyr** [comment] 2019-01-05 13:03
Moreover we cannot be sure that this is not a compatibility issue because django-notify-x does not say it supports Django 2.1

**Comment by Z-ephyr** [comment] 2019-01-05 13:44
It works! I mean not totally (eg, the "mark as read" and "X" buttons do not work), but it gets displayed! I am committing it (it is a random notification with no meaning, but at least there is display).

**Comment by MaloPerez** [comment] 2019-01-05 13:59
Great !!

**Comment by Z-ephyr** [comment] 2019-01-13 10:55
@MaloPerez It seems to me you told me you had created some "real" notifications... At which point are you ? I am working (for the moment, without results ^^') on the "X" and "mark as read" button

**Comment by Z-ephyr** [comment] 2019-01-13 10:58
To do

- [ ] "X" and "mark as read" buttons do not work
- [ ] Settings page
- [ ] Create "true" notifications
- [ ] Tests ? (I don't know how to do it)

**Comment by Z-ephyr** [comment] 2019-01-13 11:14
Interesting things are happening here http://localhost:8000/notifications/all/

**Comment by Z-ephyr** [comment] 2019-01-13 12:56
Ok the buttons work now!

**Comment by Z-ephyr** [comment] 2019-01-13 13:59
@MaloPerez you can delete my test notification now

**Comment by MaloPerez** [comment] 2019-01-13 14:20
@Z-ephyr Good job ! Having some problems but working through it !

**Comment by Z-ephyr** [comment] 2019-01-13 14:35
I think it would be nice if we did something like that for the settings : https://templates.pinaxproject.com/notifications/settings/no-confirmed-email-state/

The requirements state that: `The interface should feature notifications reminding users of nearing
events. Reminders should be configurable: enabled/disable, delay.`

For the moments, we have no delay function... I don't understand how `delay` is a configuration... Maybe we should add a button delay?

Also, we need to understand what we want to do with read notifications. Shall we delete them? If yes, what is the point of having an "X" and a "mark as read" buttons?

**Comment by Z-ephyr** [comment] 2019-01-13 17:30
@MaloPerez could you please tell me what kind of notifications you are creating? I need it to create the settings page.
It would be good to have a list somewhere on which I could iterate to create the page

**Comment by Z-ephyr** [comment] 2019-01-13 18:14
Maybe we could do the following:
- when the "X" button is pressed, the notification is deleted ;
- when the "mark as read" button is pressed, the notification is shown again after a certain delay that can be set up in the settings. The button should be renamed "delay" if possible.

**Comment by Z-ephyr** [comment] 2019-01-13 18:57
Nice :) I think you should get notifications to be reminded of upcoming events as well (at least that is what I understand from the requirements)

**Comment by Z-ephyr** [comment] 2019-01-15 12:42
@PierreGtch you committed on the `resolution` branch but we need it on the `notify` branch as well... What should we do ? "Commit again" ? Is that possible ?

**Comment by Z-ephyr** [comment] 2019-01-15 12:44
Also, for the settings page ( @PierreGtch said he would take care of it) we will have three kinds of notifications : "you have been invited to an event", "you received a friend request", "you have an upcoming event"...

@MaloPerez Didi you manage to do the "you have an upcoming event" notifications ?

**Comment by Z-ephyr** [comment] 2019-01-15 12:45
As soon as I finish my exam I shall try to take care of the "delay" part

**Comment by PierreGtch** [comment] 2019-01-15 13:23
> @PierreGtch you committed on the `resolution` branch but we need it on the `notify` branch as well... What should we do ? "Commit again" ? Is that possible ?

@Z-ephyr, @Kessaye said I just had one change to do in the resolution branch and we could push it  on master but in fact there is a bug in `balance_of_user`...

**Comment by MaloPerez** [comment] 2019-01-15 15:12
@Z-ephyr almost done, I just need to know how long in advance I need to notify for an upcoming event. I also added a notification that notifies a user as soon as someone edits an event they were invited to.

**Comment by Z-ephyr** [comment] 2019-01-15 17:51
Maybe one day before ? And when delayed the notification is set in timeremaining/2 minutes ? If the event is already done, delaying delays of 1 hour ?
For other notifications, delay is one hour ?

**Comment by MaloPerez** [comment] 2019-01-15 20:09
@Z-ephyr Are you taking care of the delay part ? I finished the notification but I'm having trouble deciding in what function to send it, for now it's in the view for the index page, but it means that the notification is resent as soon as we enter the index page (as long as the event is one day before).

**Comment by Z-ephyr** [comment] 2019-01-15 20:11
I was taking care of the bug in the search bar, I needed a break from notification ^^ so I have not done the delay

**Comment by Z-ephyr** [comment] 2019-01-15 20:12
Maybe we could change the model of event and add a `notification_sent` boolean?

**Comment by MaloPerez** [comment] 2019-01-15 20:14
@Z-ephyr Don't worry, I was just wondering ! That sounds like a good idea, and clicking the delay button could reset the notification_sent boolean to False. I don't know how to modify a model though

**Comment by Z-ephyr** [comment] 2019-01-15 20:15
you go to `models.py` and change the class
I can do it for you

**Comment by MaloPerez** [comment] 2019-01-15 20:16
That would be helpful !

**Comment by Z-ephyr** [comment] 2019-01-15 20:16
Better: not a boolean but an `int` denoting the number of notifications sent... That would be useful for delay!

**Comment by Z-ephyr** [comment] 2019-01-15 20:19
@MaloPerez done!

**Comment by Z-ephyr** [comment] 2019-01-15 20:20
`notifications_sent` is an integer field... I think it should represent the number of time a notification was sent.

**Comment by Z-ephyr** [comment] 2019-01-15 20:23
When there is a notification, either the user deletes it or delays it (or does nothing, so it stays on screen), so when the notification is still there we always want to display it
I think we should display it if (time remaining before the event) <= 1/2^(notifications_sent) day. This way each delay gives a new notification at (now+time_event)/2
What do you think?

**Comment by MaloPerez** [comment] 2019-01-15 21:09
@Z-ephyr I changed the notification that reminds the user that it has an upcoming event in less than one day if the notification has never been sent before using the notifications_sent field of the event model !

**Comment by Z-ephyr** [comment] 2019-01-15 21:58
I don't understand ^^

**Comment by Z-ephyr** [comment] 2019-01-15 21:59
So did you take care of the delay or not ? :o

**Comment by MaloPerez** [comment] 2019-01-15 22:25
No no, I just made sure that the event reminder was only sent once !

**Comment by Z-ephyr** [comment] 2019-01-16 14:20
Requirements are not really clear
`project.pdf` : `Notifications The interface should feature notifications reminding users of nearing
events. Reminders should be configurable: enabled/disable, delay`
`eval.html` : `Our requirements were not explicit about this, but a more reactive and application-wide notion of notification was expected: when a user is online, on any page, he should get some sort of popup if he received an invitation or if an event is nearing. Moreover, notifications cannot currently be configured, while the requirements explicitly asked for the ability to tune reminders.`

They don't precise if we should implement delay for other kind of notifications...
The solution we adopted for events work but to be honest it is not pretty and does not enable us to delay other kind of notifications. What we should do is, in the UserProfile, have a list of notifications to send, each one associated with a date from which to send them.
But I am not sure we have the time to implement that

**Comment by Z-ephyr** [comment] 2019-01-16 14:35
Hmm maybe... I am thinking of notifications as "to-dos" that you might not want to do immediately but may want to do later. But that maybe a wrong interpretation given the context! (Anyway, it is easier not to choose this one)

Btw @MaloPerez if you want we are in 321 in Cachan you can come and join us

**Closed** 2019-01-16 22:48 UTC
Labels: course requirement
